version: '2'
services:
  zookeeper:
    restart: always
    container_name: zookeeper
    image: wurstmeister/zookeeper
    env_file: 
    - .env    
    networks:
    - net
  kafka:
    restart: always
    container_name: kafka
    image: wurstmeister/kafka:2.13-2.6.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # https://medium.com/@marcelo.hossomi/running-kafka-in-docker-machine-64d1501d6f0b
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:7710
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://${PUBLIC_IP}:7710
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_DELETE_TOPIC_ENABLE: "true"  
      KAFKA_CREATE_TOPICS: "metricbeat:4:1"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_MESSAGE_MAX_BYTES: 15728640
      KAFKA_REPLICA_FETCH_MAX_BYTES: 15728640
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - kafka-data:/var/lib/kafka/data
    ports:
      - "7710:7710"
    depends_on:
      - zookeeper
    networks:
      - net  
volumes:
  kafka-data:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1