# on:
#   push:
#     branches:
#       - main
# name: build gatsby
# jobs:
#   build_gatsby:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1

#       - name: Get yarn cache directory path
#         id: yarn-cache-dir-path
#         run: echo "::set-output name=dir::$(yarn cache dir)"
#       - uses: actions/cache@v1
#         id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
#         with:
#          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#               ${{ runner.os }}-yarn-
#          run: npm install --global gatsby-cli

# #       - name: gatsby build
# #         env:
# #           GH_API_KEY: ${{ secrets.KMP }}
# #         run: npm run build

#       - name: deploy
#         uses: maxheld83/ghpages@v0.2.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GH_PAT: ${{ secrets.KMP }}
#           BUILD_DIR: '.'


# name: Build and Deploy
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# jobs:
#   build-and-deploy:
#     concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         run: |
#           npm ci
#           npm run build{{ github.token }}
#     - name: Deploy 🚀
#       uses: JamesIves/github-pages-deploy-action@v4.3.3
#       with:
#         token: ${{ github.KMP }}
#         branch: main
#         folder: .
#         clean: false
# #         branch: master
# #         folder: .
# #         clean: false
# #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# #         GH_PAT: ${{ secrets.KMP }}
# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
  
# name: Node.js CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: ls
# #     - run: git config --global credential.helper wincred
#     - run: npm install 
#     - run: npm install -g gatsby-cli

# #     - run: npm ci
# #     - run: npm test
# #     - name: Deploy 🚀
# #       uses: JamesIves/github-pages-deploy-action@v4.3.3
# #       with:
# #         branch: master
# #         folder: .
# #         clean: false
# #         GITHUB_TOKEN: ${{ secrets.KMP }}
# #         REPOSITORY_NAME: 3dpit/3dpit.github.io
 
#     - name: Deploy
#       uses: jamesives/github-pages-deploy-action@4.1.0
#       with:
#         GITHUB_TOKEN: ${{ secrets.KMP }}
#         BRANCH: master
#         FOLDER: out
 
# name: Gatsby Publish

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        access-token: ${{ secrets.KMP }}
        deploy-branch: master
        gatsby-args: --prefix-paths
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: master
        folder: .
        clean: false
        GITHUB_TOKEN: ${{ secrets.KMP }}
        GH_PAT: ${{ secrets.KMP }}
        single-commit: true

