# name: Build and Deploy
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# jobs:
#   build-and-deploy:
#     concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         run: |
#           npm ci
#           npm run build{{ github.token }}
#     - name: Deploy 🚀
#       uses: JamesIves/github-pages-deploy-action@v4.3.3
#       with:
#         token: ${{ github.KMP }}
#         branch: main
#         folder: .
#         clean: false
# #         branch: master
# #         folder: .
# #         clean: false
# #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# #         GH_PAT: ${{ secrets.KMP }}
# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
  
# name: Node.js CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: ls
#     - run: git config --global credential.helper wincred
#     - run: npm install 
#     - run: npm install -g gatsby-cli
#     - run: npm run deploy

#     - run: npm ci
#     - run: npm test
#     - name: Deploy 🚀
#       uses: JamesIves/github-pages-deploy-action@v4.3.3
#       with:
#         branch: master
#         folder: .
#         clean: false
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         GH_PAT: ${{ secrets.KMP }}
#         single-commit: true

name: Gatsby Publish

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        access-token: ${{ secrets.KMP }}
        deploy-branch: master
        gatsby-args: --prefix-paths
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: master
        folder: .
        clean: false
        GITHUB_TOKEN: ${{ secrets.KMP }}
        GH_PAT: ${{ secrets.KMP }}
        single-commit: true

